// This file is automatically generated. Do not edit it directly.
// PERBAIKAN SAKURA-POP: dibungkus try/catch agar situs tetap jalan (mode lokal)
// saat env Supabase belum dipasang. Aplikasi ini tidak memakai login Supabase,
// jadi kegagalan mengambil sesi auth tidak boleh menggagalkan server function.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch {
      // Supabase belum dikonfigurasi / sesi tidak tersedia: lanjut tanpa token.
      return next()
    }
  },
)
